[package]
name = "wgpu-app"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.12.1", features = [ "derive" ] }
env_logger = "0.9"
log = "0.4"
pollster = "0.2"
wgpu = "0.13.1"
winit = "0.27.2"
